### ISSUE TITLE
Problem on RN 0.50.3

### ISSUE THREAD

**Issue by evilDave** [cbrevik/webview-native-config-example#1]
Great addition btw, I'd like to see this kind of thing get into other components.

You might have seen facebook/react-native#16848 about 'Unsupported top level event type "topLoadingStart" dispatched'.

I eventually noticed your example repo and it demonstrates the same issue with react-native 0.50.3 (also with v0.51.0-rc.2)

I don't quite understand exactly what is going on in the RCTComponentData where it is adding "top" to the events and so on, but it seems like there is something not being configured at the right time there.

**Comment by cbrevik** [comment]
For anyone having this problem, it'll probably be fixed in a near-future version of React Native: https://github.com/facebook/react-native/issues/16848#issuecomment-359778081
